services:
  simulator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ev-charging-simulator
    ports:
      - "8081:8081"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=info
      - BACKEND_URL=http://localhost:8080
    networks:
      - simulator-network
    restart: unless-stopped
    volumes:
      - ./configs:/app/configs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  simulator-network:
    driver: bridge
